### ISSUE TITLE
Script cannot handle multiple files being passed at once

### ISSUE THREAD

**Issue by goose-ws** [goose-ws/sonarr-bash-announce#1]
The idiot that thought bash was a good way to write this script did not anticipate Sonarr sending multiple files at once, instead of multiple script activations for individual files. What I mean is: When Sonarr runs its "check" to see if any downloaded items need to be processed/sent to the connection script, if there are multiple items completed (e.g. 3 items completed), it will pass multiple items once (all 3 items in 1 run of the script), instead of individual items (1 item in 1 run of the script, 3 times). This is mostly an issue for small files, depending on your bandwidth. I can fix this by checking to see how many items Sonarr passed to be processed (${sonarr_episodefile_episodecount}) and if it's greater than one, splitting the variable and going from there. I'll get to that in the next week or 5...

**Comment by leonard4546** [comment]
> The idiot that thought bash was a good way to write this script did not anticipate Sonarr sending multiple files at once, instead of multiple script activations for individual files. What I mean is: When Sonarr runs its "check" to see if any downloaded items need to be processed/sent to the connection script, if there are multiple items completed (e.g. 3 items completed), it will pass multiple items once (all 3 items in 1 run of the script), instead of individual items (1 item in 1 run of the script, 3 times). This is mostly an issue for small files, depending on your bandwidth. I can fix this by checking to see how many items Sonarr passed to be processed (${sonarr_episodefile_episodecount}) and if it's greater than one, splitting the variable and going from there. I'll get to that in the next week or 5...

Hey did you ever manage to update this script?

**Comment by goose-ws** [comment]
As of a few days ago, it's actually on my to-do list to update it to solve this big, use the v3 API, add a notification for downloads stuck in queue that require manual import, and move this script to a repo with my other bash scripts. I'll probably get it done before the end of March.

**Comment by goose-ws** [comment]
I've written the new script, and tested it enough that I'm comfortable releasing it now. You can find it [in this repo](https://github.com/goose-ws/bash-scripts), it is the [sonarr-group-notifications.bash](https://github.com/goose-ws/bash-scripts/blob/main/sonarr-group-notifications.bash) file (and also the [.env file](https://github.com/goose-ws/bash-scripts/blob/main/sonarr-group-notifications.env.example)).
