### ISSUE TITLE
sed: -e expression #1, char 0: no previous regular expression

### ISSUE THREAD

**Issue by leonard4546** [goose-ws/sonarr-bash-announce#2]
2023-03-05 12:33:33.6|Error|sonarr-bash-announce.sh|sed: -e expression #1, char 0: no previous regular expression
2023-03-05 12:33:33.6|Warn|SonarrErrorPipeline|Invalid request Validation failed: 
 -- : Script exited with code: 1
 
 I'm getting this error in sonarr and not able to add this script

**Comment by goose-ws** [comment]
I'm in the process of updating this script with a total rewrite to have better logic flow and be compatible with v3. I'll leave this open so I can notify you when that becomes available, probably in the next month or so.

**Comment by goose-ws** [comment]
I've written the new script, and tested it enough that I'm comfortable releasing it now. You can find it [in this repo](https://github.com/goose-ws/bash-scripts), it is the [sonarr-group-notifications.bash](https://github.com/goose-ws/bash-scripts/blob/main/sonarr-group-notifications.bash) file (and also the [.env file](https://github.com/goose-ws/bash-scripts/blob/main/sonarr-group-notifications.env.example)).
